module.exports = Object.freeze({
	SPEED_ATTENUATION_COEFFICIENT: 0.85,
	SPEED_ATTENUATION_BIAS: 5,

	HURT_INTERVAL: 2, // tick

	PLAYER_ACCELERATION_BIAS: 0,
	PLAYER_MASS: 5,
	PLAYER_SPEED: 225,
	PLAYER_RADIUS: 22.5,
	PLAYER_MAX_HP: 150,
	PLAYER_BODY_DAMAGE: 5,
	PLAYER_COLLISION_KNOCKBACK: 400,

	MSG_TYPES: {
		JOIN_GAME: 'join_game',
		GAME_UPDATE: 'update',
		INPUT: 'input',
		GAME_OVER: 'dead',
	},

	MAP_WIDTH: 2700,
	MAP_HEIGHT: 2700,

	RENDER_DELAY: 100,

	RATED_WIDTH: 1920,
	RATED_HEIGHT: 1080,

	NEARBY_DISTANCE: 1500,
});